version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge